base_url = "https://acm.umn.edu/"
build_search_index = false
compile_sass = true
generate_feed = true
feed_filename = "rss.xml"
highlight_code = true
title = "GopherHack"

# Enable if you want to check, but this is slow and dip doesn't send us back logs afaik.
# check_external_links = true

taxonomies = [
    {name = "tags", rss = true}
]
